#!/usr/bin/env node
/**
 * Generates the assets that can't be produced at request time:
 *   public/og.png              social card (headless Chrome screenshot)
 *   public/apple-touch-icon.png
 *   public/avatar.svg          monogram placeholder, only if you haven't supplied one
 *   public/favicon.svg, robots.txt
 *   dist/index.html            fully static copy, for serving the page off a CDN
 *   dist/headers.txt           the CSP header that matches dist/index.html
 *
 * Run it after editing links.json if the name, bio, avatar or link list changed.
 * The page itself needs no build — the server re-reads links.json on every change.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { extname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { ROOT, loadEnv, loadSite } from '../src/config.mjs';
import { renderPage } from '../src/render.mjs';
import { renderOgHtml, renderIconHtml } from '../src/og.mjs';

loadEnv();
const ogOnly = process.argv.includes('--og-only');
const PUBLIC = join(ROOT, 'public');
const DIST = join(ROOT, 'dist');
const GENERATED = '<!-- generated by scripts/build.mjs; delete this line to keep your own -->';

const CHROME_CANDIDATES = [
  process.env.CHROME_PATH,
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/Applications/Chromium.app/Contents/MacOS/Chromium',
  '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
  '/usr/bin/google-chrome',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/chromium',
  '/usr/bin/chromium-browser',
  '/snap/bin/chromium',
].filter(Boolean);

const findChrome = () => CHROME_CANDIDATES.find((p) => existsSync(p)) || null;

function screenshot(chrome, html, out, width, height) {
  const tmp = join(tmpdir(), `linkinbio-${Date.now()}-${Math.random().toString(36).slice(2)}.html`);
  writeFileSync(tmp, html);
  const args = [
    '--headless=new', '--disable-gpu', '--no-sandbox', '--disable-dev-shm-usage',
    '--hide-scrollbars', '--force-device-scale-factor=1', '--force-color-profile=srgb',
    `--window-size=${width},${height}`, `--screenshot=${out}`, `file://${tmp}`,
  ];
  try {
    execFileSync(chrome, args, { stdio: 'pipe' });
  } catch {
    // Older builds don't understand --headless=new.
    execFileSync(chrome, ['--headless', ...args.slice(1)], { stdio: 'pipe' });
  } finally {
    rmSync(tmp, { force: true });
  }
}

/** Inline the avatar so Chrome can render it from a file:// page. */
function avatarDataUri(site) {
  if (!site.avatar || /^https?:/i.test(site.avatar)) return '';
  const file = join(PUBLIC, site.avatar.replace(/^\//, ''));
  if (!existsSync(file)) return '';
  const type = { '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.webp': 'image/webp', '.gif': 'image/gif' }[extname(file).toLowerCase()];
  if (!type) return '';
  return `data:${type};base64,${readFileSync(file).toString('base64')}`;
}

function monogram(name) {
  const initials = name.trim().split(/\s+/).slice(0, 2).map((w) => w[0]).join('').toUpperCase() || '·';
  return `${GENERATED}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 144 144" width="144" height="144" role="img" aria-label="${initials}">
  <rect width="144" height="144" rx="28" fill="#e2e6f7"/>
  <rect x="0.5" y="0.5" width="143" height="143" rx="27.5" fill="none" stroke="#c3cbe8"/>
  <text x="72" y="72" fill="#2440e8" font-family="Iowan Old Style, Palatino Linotype, Palatino, Georgia, serif"
    font-size="62" font-weight="500" letter-spacing="-1" text-anchor="middle" dominant-baseline="central">${initials}</text>
</svg>
`;
}

const FAVICON = `${GENERATED}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32">
  <rect width="32" height="32" rx="7" fill="#2440e8"/>
  <path d="M10 22 22 10M12.6 10H22v9.4" fill="none" stroke="#eef1ff" stroke-width="3"
    stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;

const ROBOTS = `User-agent: *
Allow: /
Disallow: /go/
Disallow: /stats
`;

/** Write only if missing, or if we wrote the current version ourselves. */
function writeUnlessCustom(file, contents, label) {
  if (existsSync(file) && !readFileSync(file, 'utf8').includes(GENERATED)) {
    console.log(`  keep    ${label} (yours)`);
    return;
  }
  writeFileSync(file, contents);
  console.log(`  write   ${label}`);
}

/* ------------------------------------------------------------------ */
mkdirSync(PUBLIC, { recursive: true });
const site = loadSite();
for (const w of site.warnings) console.warn(`  ! links.json  ${w}`);

console.log(`\nBuilding assets for "${site.name}" (${site.links.length} links)\n`);

if (!ogOnly) {
  writeUnlessCustom(join(PUBLIC, 'avatar.svg'), monogram(site.name), 'public/avatar.svg');
  writeUnlessCustom(join(PUBLIC, 'favicon.svg'), FAVICON, 'public/favicon.svg');
  if (!existsSync(join(PUBLIC, 'robots.txt'))) {
    writeFileSync(join(PUBLIC, 'robots.txt'), ROBOTS);
    console.log('  write   public/robots.txt');
  }
}

const chrome = findChrome();
if (!chrome) {
  console.warn(
    '\n  ! No Chrome/Chromium found, so og.png and apple-touch-icon.png were skipped.\n' +
    '    Install one, or point CHROME_PATH at it, then run `npm run og`.\n' +
    '    On Debian/Ubuntu: sudo apt install -y chromium\n'
  );
} else {
  const ogSite = { ...site, avatarData: avatarDataUri(site) };
  screenshot(chrome, renderOgHtml(ogSite), join(PUBLIC, 'og.png'), 1200, 630);
  console.log('  render  public/og.png            1200x630');
  screenshot(chrome, renderIconHtml(), join(PUBLIC, 'apple-touch-icon.png'), 180, 180);
  console.log('  render  public/apple-touch-icon.png  180x180');
}

if (!ogOnly) {
  mkdirSync(DIST, { recursive: true });
  const page = renderPage(site);
  writeFileSync(join(DIST, 'index.html'), page.html);
  writeFileSync(
    join(DIST, 'headers.txt'),
    `# Content-Security-Policy for dist/index.html.\n` +
    `# Regenerate with \`npm run build\` whenever links.json changes — the hash covers the inline <style>.\n\n` +
    `Content-Security-Policy: default-src 'none'; img-src 'self' data: https:; style-src '${page.styleHash}'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'\n`
  );
  console.log('  write   dist/index.html          static copy');
  console.log('  write   dist/headers.txt         CSP for the static copy');
}

console.log('\nDone.\n');
